### ISSUE TITLE
atletter_to_color_value does not exist

### ISSUE THREAD

**Issue by michaeldnelson** [endavis/bastmush#14]
Was having problems with minwin_eq.  It appears to be related to this missing dictionary/table/array? 
atletter_to_color_value in minwin.lua. When I remove this reference everything works but id becomes black and white.

x = x + wfunction (self.winid, font_id, text, x, Top, Right, Bottom,
                                 atletter_to_color_value[colour] or self.text_colour)

Run-time error
Plugin: miniwin_eq (called from world: Aardwolf)
Function/Sub: onitemchange called by Plugin miniwin_eq
Reason: Executing plugin miniwin_eq sub onitemchange
C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:1952: attempt to index global 'atletter_to_color_value' (a nil value)
stack traceback:
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:1952: in function 'colourtext'
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:1640: in function 'justify_line'
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:1840: in function 'pre_create_window_internal'
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:2579: in function 'drawwin'
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:1217: in function 'redraw'
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:528: in function 'resettabs'
        C:\Muds\MUSHclient\worlds\plugins\Bast\lua\miniwin.lua:475: in function 'addtab'
        [string "Plugin: miniwin_eq"]:481: in function 'builditem'
        [string "Plugin: miniwin_eq"]:1088: in function <[string "Plugin: miniwin_eq"]:1080>

**Comment by fiendish** [comment]
it does in aardwolf mushclient package r1919
