### ISSUE TITLE
Recent GQ change 

### ISSUE THREAD

**Issue by Kerowyn** [endavis/bastmush#3]
The recent change to GQs has broken most of the Bast plugins ability to capture GQ wins and qps.  

Wondering if an update is forthcoming?  

Thanks, 

Kerowyn
@AardKerowyn

**Comment by endavis** [comment]
Yes, I will update the plugins, it will probably be in the next 2 weeks.

**Comment by endavis** [comment]
New release that includes fixes for the new gq format in r2095
